# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbridgeWrite < Formula
  desc "Write-capable database CLI and MCP server for AI agents"
  homepage "https://github.com/thalesfp/dbridge"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.8.0/dbridge-write_0.8.0_darwin_amd64.tar.gz"
      sha256 "d6212e8e0b882b9cfd7241569608a45f4af13548d3fc05276b70bc7a94dba925"

      define_method(:install) do
        bin.install "dbridge-write"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.8.0/dbridge-write_0.8.0_darwin_arm64.tar.gz"
      sha256 "aecd2d9f9a1433812f2fa7c5165252607d11ce895691a179983fb13aad300c34"

      define_method(:install) do
        bin.install "dbridge-write"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.8.0/dbridge-write_0.8.0_linux_amd64.tar.gz"
      sha256 "57eac1ec895f0eb282b078a9fc77a17fbf6e55999ac7945e7f22a451523c8ac1"
      define_method(:install) do
        bin.install "dbridge-write"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.8.0/dbridge-write_0.8.0_linux_arm64.tar.gz"
      sha256 "54b98fba9a45d20eec047a4955a03c8ef8fb48189163b54d792060d6725005cc"
      define_method(:install) do
        bin.install "dbridge-write"
      end
    end
  end
end
