# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbridge < Formula
  desc "Multi-database CLI and MCP server for AI agents"
  homepage "https://github.com/thalesfp/dbridge"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.8.0/dbridge_0.8.0_darwin_amd64.tar.gz"
      sha256 "6e9472df38cf62ec35653caff5add961bb615e83a4e7b5244c256818c8f46f67"

      define_method(:install) do
        bin.install "dbridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.8.0/dbridge_0.8.0_darwin_arm64.tar.gz"
      sha256 "982d75c2a4e24e0871e4ba726067cf94e4a85c3ac5cfada1f4e0e3ad8373d03b"

      define_method(:install) do
        bin.install "dbridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.8.0/dbridge_0.8.0_linux_amd64.tar.gz"
      sha256 "4d95529198e689ee9bf2297522331f1fbdc23afb3a15984b049678192068e3c7"
      define_method(:install) do
        bin.install "dbridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.8.0/dbridge_0.8.0_linux_arm64.tar.gz"
      sha256 "c67088c7608cf19224f2703ec91cb698f4321edd0889f887c0bc2e3cc90e5afe"
      define_method(:install) do
        bin.install "dbridge"
      end
    end
  end
end
