# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbridge < Formula
  desc "Multi-database CLI and MCP server for AI agents"
  homepage "https://github.com/thalesfp/dbridge"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.5.1/dbridge_0.5.1_darwin_amd64.tar.gz"
      sha256 "ced170577781a630631282cf57161d46f03676974a97cfa4b71a83ee1114145f"

      define_method(:install) do
        bin.install "dbridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.5.1/dbridge_0.5.1_darwin_arm64.tar.gz"
      sha256 "694bafafa6f9af9af0041629bc5caf1a8c1d448f355f3318fb3732fd454a9eeb"

      define_method(:install) do
        bin.install "dbridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.5.1/dbridge_0.5.1_linux_amd64.tar.gz"
      sha256 "92fcbc4a10716f03f9da6bb19ee1ccd3eb6b8988a59a16890c23fd0ecb8ea75d"
      define_method(:install) do
        bin.install "dbridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thalesfp/dbridge/releases/download/v0.5.1/dbridge_0.5.1_linux_arm64.tar.gz"
      sha256 "b9d682f07345af418f633d07439df6a76ec55081a17a3739a06374dd8b9b82d1"
      define_method(:install) do
        bin.install "dbridge"
      end
    end
  end
end
